### ISSUE TITLE
DELTA DATAPACK NOT WORKING ON MC 1.20.2

### ISSUE THREAD

**Issue by SupFede** [BigPapi13/Delta#16]
greetings, currently the whole datapack cannot work on the latest version of Minecraft being 1.20.2.
That's really all, i hope it gets fixed soon since i was working on a datapack.

**Comment by Nico314159** [comment]
I have the same issue and I'm not sure exactly why. I assume it may relate to an NBT key being renamed or Minecraft's subtick timings being changed.

**Comment by SupFede** [comment]
If the dev of this mod is checking out this section, PLEASE FIX THIS SO IT CAN BE PLAYED ON 1.20.2

**Comment by Nico314159** [comment]
> If the dev of this mod is checking out this section, PLEASE FIX THIS SO IT CAN BE PLAYED ON 1.20.2

It's been fixed on the `no-rp` branch. No need to lose your cool.

**Comment by SupFede** [comment]
aight but where be that?
